### PR TITLE
#162727470 User rate articles

### PR DESCRIPTION
**Pull request by Proception**
#### What does this PR do?
It implements the functionality of each user being able to rate a post. It also has validations, tests, and models for the implementation.

#### Description of Task to be completed?
- Implement user rate post functionality
- write test for the functionality
- Add models for rating summary

#### How should this be manually tested?
- checkout the branch
- run `npm install`
- run `npm test`
- use postman to test the following endpoints
- send a `POST` request with a logged in user to `/api/v1/rate/:artId` and pass in the following parameters in the body of the request `{rating: 1}` to test rating a user. Range is between `1 and 5`
- send a`GET` request with a logged in user to `/api/v1/rate/:artId` to get the calculated rating for art.
- send a `GET` request with a logged in user to `/api/v1/rate/:artId/user` to get the rating a user gave to an article

#### Any background context you want to provide?
- A user can not rate another user's post more than once
- The creator of a content can not rate his own item

#### What are the relevant pivotal tracker stories?
[#162727470](https://www.pivotaltracker.com/story/show/162727470)

#### Screenshots (if appropriate)
N/A
#### Questions:
NA

### CODE REVIEW

**Review by daniellamarr — APPROVED** [review]
Very good

**Review by wombolo — APPROVED** [review]
LGTM

**Review by julietezekwe — APPROVED** [review]
Looks good

**Comment by abejide001** [comment]
LGTM

**Review by abejide001 — APPROVED** [review]
LGTM

**Review by andela-dbamidele — APPROVED** [review]

**Pull request merged**
